function newMuscle(parentf,muscleNameH)


tag=[];
if(nargin==0)
parentf=gcbf;
tag=get(gcbo,'Tag');
end
if(strcmp(tag,'Edit'))
% 	muscleNameH=get(gcbo,'UserData');
% 	value=get(muscleNameH,'Value');
% 	muscleNames=get(muscleNameH,'String');
% 	muscleName=muscleNames(value,:);
% 	muscleName=muscleName{1};
	muscleNameH=get(gcbo,'UserData');
    value=get(muscleNameH,'Value');
	muscleNames=get(muscleNameH,'String');
	muscleName=muscleNames(value,:);
	muscleName=muscleName{1};
	muscleNameWUScore=muscleName;
	posIndex=find(muscleName=='_');
	if(~isempty(posIndex))
		muscleName=muscleName(1:posIndex(end));
		muscleNameWUScore=muscleName(1:posIndex(end)-1);
	end
	indexCustoms=find(strncmp(lower(muscleNames),lower(muscleName),length(muscleName)));
    indexes=[];
   if(~isempty(indexCustoms))
	   for i=1:length(indexCustoms);
		   int=str2num(muscleNames{indexCustoms(i)}((length(muscleName)+1):end));
		   if(~isempty(int))
			   indexes(end+1)=int;
		   end
	   end
	   indexes=sort(indexes);
	   cMuscleName=[muscleNameWUScore,'_',num2str(length(indexes)+1)];
	   for i=length(indexes):-1:1
		   if(indexes(i)-i>0)
			   cMuscleName=[muscleNameWUScore,'_',num2str(i)];
		   end
	   end
	  muscleName=cMuscleName;
   else
	  muscleName=[muscleNameWUScore,'_1'];
   end
	
else
   muscleNames=get(muscleNameH,'String');
   indexCustoms=find(strncmp(lower(muscleNames),'custom_',7));
   indexes=[];
   if(~isempty(indexCustoms))
	   for i=1:length(indexCustoms);
		   int=str2num(muscleNames{indexCustoms(i)}(8:end));
		   if(~isempty(int))
			   indexes(end+1)=int;
		   end
	   end
	   indexes=sort(indexes);
	   muscleName=['Custom_',num2str(length(indexes)+1)];
	   for i=length(indexes):-1:1
		   if(indexes(i)-i>0)
			   muscleName=['Custom_',num2str(i)];
		   end
	   end
   else
	   muscleName='Custom_1';
   end
end
userData=get(parentf,'UserData');
simulatormfc=userData.simulatormfc;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Get the screen size
screenSize=get(0,'ScreenSize');
screenHeight=screenSize(4);
screenWidth=screenSize(3);

%figure height and width
figureWidth=475;
figureHeight=500;
backGroundColor=[0.98,0.98,0.98];
%margin
margin=0.01;

%Main figure
f=figure(...
	'Name','Muscle',...
	'NumberTitle','off',...
	'MenuBar','none',...
	'Units','pix',...
	'Resize','off',...
	'defaultaxesxtick', [], ...
	'CloseRequestFcn',@cancel,...
	'defaultaxesytick', [], ...
	'defaultuicontrolcallback',@checkValue,...
	'pos',[(screenWidth-figureWidth)/2,(screenHeight-figureHeight)/2,figureWidth,figureHeight]);

%----------------------------Main Panel ----------------------------------------

panelHeight=0.98;
generalRowHeight=panelHeight/22;
leftPanelMargin=0.05;
editBoxPosX=0.30;
textBoxWidth=0.37;
browseField=0.50;
editBoxWidth=0.35;
checkBoxPosX=0.05;
editBoxStartY=panelHeight+margin;

%-------------------Tabs-------------------------------------------------

numberOfTabs=2;
buttonWidth=(1-2*margin)/numberOfTabs;
buttonHeight=1/18;
backGroundColor=[0.98,0.98,0.98];

%Muscle tab
tab(1)=uicontrol(...
	'parent',f,...
	'style','pushbutton',...
	'Units','normalized',...
	'String','Muscle',...
	'BackgroundColor',backGroundColor,...
	'Callback',@selectTab,...
	'pos',[margin,1-margin-buttonHeight,buttonWidth,buttonHeight]);

%Motoneuron Pool tab
tab(2)=uicontrol(...
	'parent',f,...
	'style','pushbutton',...
	'Units','normalized',...
	'String','Motorneuron Pool',...
	'Callback',@selectTab,...
	'pos',[margin+buttonWidth,1-margin-buttonHeight,buttonWidth,buttonHeight]);


panelEdge=uicontrol(...
	'style','text',...
	'Units','norm',...
	'pos',[margin,1-margin-buttonHeight,1-2*margin,0.0125],...
	'BackgroundColor',backGroundColor);

currentTabTop=uicontrol(...
	'style','text',...
	'Units','norm',...
	'pos',[margin,1-margin-0.005,buttonWidth,0.0075],...
	'BackgroundColor',[1,0.70,0.25]);
panelHeight=panelHeight-buttonHeight;
panel=axes(...
	'parent',f,...
	'Units','norm',...
	'Xcolor',backGroundColor,...
	'Ycolor',backGroundColor,...
	'Color',backGroundColor,...
	'pos',[margin,margin+buttonHeight,1-2*margin,panelHeight-buttonHeight]);
	
%----------------------Figure User Data----------------------------------
% The figure USerData conatins the handles of the tabs,
% the curent configuration 
preferences=[];
figureData= struct(...
	'tabsData',tab,...
	'currentTabTop',currentTabTop,...
	'simulatormfc',simulatormfc,...
	'preferences', preferences);

set(f,'UserData',figureData);

generalTabHandles=[];
%%%%%%%%%%%%%%%%%%%%%%%%UICONTROLS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%-----------------------------Muscle Tab---------------------------------
%----------------------ROW 1--------------------------------------------
editBoxY=3.5*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Muscle name:',...
	'UserData','f',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);
defaultFontName= get(generalTabHandles(1),'FontName');
defaultFontSize= get(generalTabHandles(1),'FontSize');

%--------Set default font and Size--------------
set(f,...
	'defaultuicontrolFontName',defaultFontName,...
	'defaultuicontrolFontSize',defaultFontSize);
%---------------------------------------------

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','muscleName',...
	'Units','norm',...
	'horizontalAlignment','left',...
	'BackgroundColor',backGroundColor,...
	'String',muscleName,...
	'UserData',f,...
	'pos',[leftPanelMargin+textBoxWidth,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','pushButton',...
	'Tag','configFile',...
	'Units','norm',...
	'horizontalAlignment','left',...
	'String','Load Muscle...',...
	'Callback',@loadCFGFile,...
	'UserData',generalTabHandles(end),...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

%----------------------ROW 2--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Number of MUs in muscle:',...
	'UserData','f',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);


generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String','',...
	'Tag','nmu_in_mscl',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);



%----------------------ROW 3--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Muscle fiber density (per mm^2):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String','',...
	'Tag','mscl_fib_dens',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

%----------------------ROW 4--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Muscle fiber area (mm^2):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','mscl_area_per_fib',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String','',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);



%----------------------ROW 5--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Motor unit diameter:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Min:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin+0.54,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','min_mu_diam',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 6--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Max:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin+0.54,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','max_mu_diam',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 7--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;

generalTabHandles(end+1)=uicontrol(...
	'style','checkbox',...
	'Tag','doJitter',...
	'String','Enable Jitter',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'UserData',f,...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY,editBoxWidth,generalRowHeight]);


generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Jitter variance(us):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin+0.4,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','jitter',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 8--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;


generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Neuropathic MU Loss Fraction:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','pathology_neuropathy_MU_loss_fraction',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[leftPanelMargin+textBoxWidth,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
generalTabHandles(end+1)=uicontrol(...
	'style','pushbutton',...
	'Tag','electrode_type',...
	'Units','norm',...
	'String','Advanced ',...
	'Callback','advancedNeuropathic',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 9--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;


generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Myopathic Fibre Affected Fraction:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','right',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','pathology_myopathy_fibre_affected_fraction',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[leftPanelMargin+textBoxWidth,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
generalTabHandles(end+1)=uicontrol(...
	'style','pushbutton',...
	'Tag','electrode_type',...
	'Units','norm',...
	'String','Advanced ',...
	'Callback','advancedMyopathic',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
set(tab(1),'UserData',generalTabHandles);
set(generalTabHandles,'Visible','off');
%----------------------Buttons--------------------------------------------
editBoxY=editBoxY+2.5*generalRowHeight;

uicontrol(...
	'style','pushButton',...
	'Tag','electrode_type',...
	'Units','norm',...
	'String','Save As',...
	'Callback',@saveConfiguration,...
	'UserData',f,...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

h=uicontrol(...
	'style','pushButton',...
	'Tag','electrode_type',...
	'Units','norm',...
	'String','OK',...
	'callback',@checkMuscle,...
	'UserData',muscleNameH,...
	'pos',[leftPanelMargin+browseField/2+0.075,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%if(strcmp(tag,'Edit'))
	%set(h,'callback',@saveChangesToMuscle);
%end
	
uicontrol(...
	'style','pushButton',...
	'Tag','Exit',...
	'Units','norm',...
	'String','Cancel',...
	'Callback',@cancel,...
	'UserData',muscleNameH,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

%----------------------------Motorneuron Pool----------------------------
generalTabHandles=[];
%----------------------ROW 1--------------------------------------------
editBoxY=3.5*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Max recruitment threshold (% MVC):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,textBoxWidth,generalRowHeight]);


generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','firing_maximumFiringThreshold',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String','',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);



%----------------------ROW 2--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','IPI firing slope (pps/(%MVC)):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','firing_recruitmentSlope',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String','',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);


%----------------------ROW 3--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Firing rate:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);


%----------------------ROW 4--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Min (pps):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin+0.1,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','firing_minimumFiringRate',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 5--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;
generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Max (pps):',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin+0.1,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','firing_maximumFiringRate',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);
%----------------------ROW 6--------------------------------------------
editBoxY=editBoxY+2*generalRowHeight;


generalTabHandles(end+1)=uicontrol(...
	'style','text',...
	'String','Coeff of variance:',...
	'Units','norm',...
	'BackgroundColor',backGroundColor,...
	'horizontalAlignment','left',...
	'pos',[leftPanelMargin,editBoxStartY-editBoxY-0.25*generalRowHeight,editBoxWidth,generalRowHeight]);

generalTabHandles(end+1)=uicontrol(...
	'style','edit',...
	'Tag','coefficientOfVarianceInFiringTimes',...
	'Units','norm',...
	'horizontalAlignment','right',...
	'BackgroundColor',backGroundColor,...
	'String',' ',...
	'UserData',f,...
	'pos',[1-leftPanelMargin-browseField/2,editBoxStartY-editBoxY,browseField/2,generalRowHeight]);

set(tab(2),'UserData',generalTabHandles);
set(generalTabHandles,'Visible','off');

tabHandles=get(tab(1),'UserData');
set(tabHandles,'Visible','on');
fillIn(f,f);
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SELECTTAB
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function selectTab(src,evnt)

backGroundColor=[0.98,0.98,0.98];
currentTab=gco;
f=get(currentTab,'parent');
figureData=get(f,'UserData');
for i=1:length(figureData.tabsData)
	generalTabHandles=get(figureData.tabsData(i),'UserData');
	set(generalTabHandles,'visible','off');
end


set(figureData.tabsData,'BackgroundColor',[0.878,0.875,0.89]);
set(currentTab,'BackgroundColor',backGroundColor);
posButton=get(currentTab,'pos');
posEdge= get(figureData.currentTabTop,'pos');
posEdge(1)=posButton(1);
set(figureData.currentTabTop,'pos',posEdge);
generalTabHandles=get(currentTab,'UserData');
set(generalTabHandles,'visible','on');
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%FILLIN
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function fillIn(f,parentf)

figureUserData=get(parentf,'UserData');
% get the simulatormfc structure
simulatormfc=figureUserData.simulatormfc;
h=findobj(f,'style','edit');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=getfield(simulatormfc,field);
		value=value.value;
		set(h(i),'String',value);
	end
end
h=findobj(f,'style','checkbox');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=getfield(simulatormfc,field);
		value=str2num(value.value);
		if(~isempty(value))
			set(h(i),'Value',value);
		end
	end
end
h=findobj(f,'style','popupmenu');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=getfield(simulatormfc,field);
		value=str2num(value.value);
		if(~isempty(value))
			set(h(i),'Value',value);
		end
	end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%checkValue
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function checkValue(src,evnt)
simulator=get(gcbo,'UserData');
figureUserData=get(simulator,'UserData');
simulatormfc=figureUserData.simulatormfc;
field=get(gcbo,'Tag');
style=get(gcbo,'style');
if(isfield(simulatormfc,field))
	if(strcmp(style,'edit'))

		fieldStruct=getfield(simulatormfc,field);
		fieldStruct.value=get(gcbo,'String');
		if (isempty(fieldStruct.range))
		elseif(length(fieldStruct.range)<2)
			if(str2num(fieldStruct.value)< fieldStruct.range)
				message=['The value should be greater than ', num2str(fieldStruct.range),' !'];
				h=warndlg(message);
			end
		else
			if((str2num(fieldStruct.value)< fieldStruct.range(1))&(str2num(fieldStruct.value)>fieldStruct.range(2)))
				message=['The value should be between ', num2str(fieldStruct.range(1)),' and ',num2str(fieldStruct.range(2)),' !'];
				h=warndlg(message);
			end

		end


	end
end
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%saveConfiguration
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function saveConfiguration(src,evnt)
f=gcbf;
updateCFG(f,f);
h=findobj(f,'Tag','muscleName');
muscleName='Muscle';
if(ishandle(h))
	muscleName=get(h,'string');
	if (isempty(muscleName))
		muscleName='Muscle';
	end
end
muscleName=fullfile(cd,'Muscles',muscleName);
[fileName,pathName,FilterIndex] = uiputfile('.cfg','Save the Muscle configuration',muscleName);
cfgFile=fullfile(pathName,fileName);
if(fileName~=0)
	simulator=gcbf;
    figureUserData=get(gcbf,'UserData');
    simulatormfc=figureUserData.simulatormfc;
	newFileLine=[];
	fid=fopen('default.cfg','r');
	tline=fgetl(fid);

	while tline~=-1
		[field,count,errmsg,nextIndex]=sscanf(tline,'%s',1);
		if(isfield(simulatormfc,field))
			[equalSign,count,errmsg,nextIndex]=sscanf(tline,'%s',2);
			value=tline(nextIndex:end);
			value=strtrim(value);
            %value=deblank(value);
			tline=tline(1:nextIndex);

			if (value(1)=='"')
				s=getfield(simulatormfc,field);
				s=s.value;
				s=regexprep(s,'\\','\\\');
				tline=[tline,'"',s,'"',';'];
			else
				s=getfield(simulatormfc,field);
				s=s.value;
				tline=[tline,s,';'];
			end
		end

		newFileLine{end+1}=tline;
		tline=fgetl(fid);
	end


	fclose(fid);

	
	fid=fopen(cfgFile,'w');

	for i=1:length(newFileLine)
		fprintf(fid,'%s\n',newFileLine{i});

	end
	fclose(fid);
end
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%updateCFG
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function updateCFG(f,parentf)

figureUserData=get(parentf,'UserData');
% get the simulatormfc structure
simulatormfc=figureUserData.simulatormfc;
h=findobj(f,'style','edit');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=get(h(i),'String');
		fieldStruct=getfield(simulatormfc,field);
	    fieldStruct.value=value;
	    simulatormfc=setfield(simulatormfc,field,fieldStruct);
		
	end
end
h=findobj(f,'style','checkbox');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=get(h(i),'Value');
		fieldStruct=getfield(simulatormfc,field);
	    fieldStruct.value=num2str(value);
	    simulatormfc=setfield(simulatormfc,field,fieldStruct);
		
	end
end
h=findobj(f,'style','popupmenu');
for i=1:length(h)
	field=get(h(i),'Tag');
	if(isfield(simulatormfc,field))
		value=get(h(i),'Value');
		fieldStruct=getfield(simulatormfc,field);
	    fieldStruct.value=num2str(value);
	    simulatormfc=setfield(simulatormfc,field,fieldStruct);
		
	end
end
figureUserData.simulatormfc=simulatormfc;
set(parentf,'UserData',figureUserData);
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%checkMuscle
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function checkMuscle(src,evnt)
f=gcbf;
muscleNamesH=get(gcbo,'UserData');
h=findobj(f,'Tag','muscleName');
muscleName='Muscle';
if(ishandle(h))
	muscleName=get(h,'string');
	if (isempty(muscleName))|(strcmp(lower(muscleName),'custom...'))
		muscleName='Muscle';
	end
end
strValues=get(muscleNamesH,'String');

index=0;
for i=1:length(strValues)-1;
 	temp=strValues(i,:);
	if(strcmp(lower(temp),lower(muscleName)))
	 	index=i;
       break;
			
	end
 end
 if(index>0)
	 button = questdlg('The Muscle already exists!  Do you want to replace it?','Select Muscle To Save ','Yes','Cancel','Cancel');
	 if(strcmp(button,'Yes'))
		 saveChangesToMuscle(f,muscleNamesH,muscleName,index)
	 end
 else
	 createMuscle(f,muscleNamesH,muscleName);
 end
			
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%saveChangesToMuscle
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%function saveChangesToMuscle(src,evnt)
function saveChangesToMuscle(f,muscleNamesH,muscleName,index)
%f=gcbf;
updateCFG(f,f);
figureUserData=get(f,'UserData');
simulatormfc=figureUserData.simulatormfc;
%parentf=get(gcbo,'UserData');
%muscleNamesH=get(gcbo,'UserData');
parentf=get(muscleNamesH,'parent');
userData=get(parentf,'UserData');
userData.simulatormfc=simulatormfc;
set(parentf,'UserData',userData);
%h=findobj(parentf,'Tag','currentMuscle');
%muscleNameH=findobj(f,'Tag','muscleName');
%muscleName=get(muscleNameH,'String');
%muscleValue=get(muscleNamesH,'Value');
muscleValue=index;
muscles=get(muscleNamesH,'UserData');
newmuscle=muscles(muscleValue);
% if(~isempty(muscleName))
% 	strValues=get(muscleNamesH,'String');
% 	for i=1:length(strValues)-1;
% 		temp=strValues(i,:);
% 		str{i}=temp{1};
% 	end
% 	str{muscleValue}=muscleName;
% 	%str{end+1}='__________';
% 	str{end+1}='Custom...';
% 	set(muscleNamesH,'String',str);
% end
newmuscle.muscleCFG=simulatormfc;
muscles(muscleValue)=newmuscle;
set(muscleNamesH,'UserData',muscles);
set(muscleNamesH,'Value',muscleValue);


delete(f);
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%createMuscle
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function createMuscle(f,muscleNamesH,muscleName)
%f=gcbf;
updateCFG(f,f);
figureUserData=get(f,'UserData');
simulatormfc=figureUserData.simulatormfc;
%parentf=get(gcbo,'UserData');
%muscleNamesH=get(gcbo,'UserData');
parentf=get(muscleNamesH,'parent');
userData=get(parentf,'UserData');
userData.simulatormfc=simulatormfc;
set(parentf,'UserData',userData);
%h=findobj(parentf,'Tag','currentMuscle');
% muscleNameH=findobj(f,'Tag','muscleName');
% muscleName=get(muscleNameH,'String');
% if(isempty(muscleName))
% 	muscleName='Custom01';
% end
muscles=get(muscleNamesH,'UserData');
newmuscle=muscles(end);
newmuscle.muscleName=muscleName;
newmuscle.muscleCFG=simulatormfc;
muscles(end+1)=newmuscle;
set(muscleNamesH,'UserData',muscles);
strValues=get(muscleNamesH,'String');
for i=1:length(strValues)-1;
 	temp=strValues(i,:);
	str{i}=temp{1};
 end
str{end+1}=muscleName;
%str{end+1}='__________';
str{end+1}='Custom...';
set(muscleNamesH,'String',str);
set(muscleNamesH,'Value',length(muscles));


delete(f);

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%LOADCFGFILE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function loadCFGFile(src,evnt,simulator)
if nargin<3
% get the callback figure
simulator=gcbf;
figureUserData=get(simulator,'UserData');
% get the simulatormfc structure
simulatormfc=figureUserData.simulatormfc;


%Get the file
[fileName,pathName,filterIndex] = uigetfile('.cfg');
fullFilePath=fullfile(pathName,fileName);
else
	%fullFilePath=fullfile(cd,'tempsimulator.cfg');
	figureUserData=get(simulator,'UserData');
    %get the simulatormfc structure
	fullFilePath=figureUserData.preferences.configFile;
    simulatormfc=figureUserData.simulatormfc;
end

%open the file
fid=fopen(fullFilePath);
if(fid~=-1)
	nameField=get(gcbo,'UserData');
	if(ishandle(nameField))
		[pathF,nameF,extF,versnF] =fileparts(fileName);
		set(nameField,'String',nameF);
	end
	tline=fgetl(fid);
	while tline~=-1
		[field,count,errmsg,nextIndex]=sscanf(tline,'%s',1);
		if(isfield(simulatormfc,field))
			tline=tline(nextIndex:end);
			[equalSign,count,errmsg,nextIndex]=sscanf(tline,'%s',1);
			value=tline(nextIndex:end);
			value=strtrim(value);
            %value=deblank(value);
			if(value(end)==';')
				value=value(1:end-1);
			end
			if (value(1)=='"')
				value=value(2:end-1);
				value=regexprep(value,'\\\','\\');
				fieldstruct=getfield(simulatormfc,field);
				fieldstruct.value=value;
				simulatormfc=setfield(simulatormfc,field,fieldstruct);
			else
				fieldstruct=getfield(simulatormfc,field);
				fieldstruct.value=value;
				simulatormfc=setfield(simulatormfc,field,fieldstruct);
			end
		end

		tline=fgetl(fid);
	end
	fclose(fid);
	figureUserData.simulatormfc=simulatormfc;
	set(simulator,'UserData',figureUserData);
	fillIn(simulator,simulator);

end
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Cancel
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function cancel(src,evnt)
f=gcbf;
h=findobj(f,'Tag','Exit');
if(ishandle(h))
	muscleNameH=get(h,'UserData');
	value=get(muscleNameH,'Value');
	muscles=get(muscleNameH,'UserData');
	if(value > length(muscles))
		set(muscleNameH,'Value',1);
		parentf=get(muscleNameH,'parent');
		userData=get(parentf,'UserData');
		userData.simulatormfc=muscles(1).muscleCFG;
		set(parentf,'UserData',userData);
	end
end
	
delete(gcbf);

